# The URL the site will be built for
base_url = "https://handcrafted-software.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "juice"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
juice_logo_name = "Handcrafted Software"
juice_logo_path = "./plaid.png"
juice_extra_menu = [
    { title = "Github", link = "https://github.com/handcrafted-software/handcrafted-software.github.io"}
]
juice_exclude_menu = [
    "exclude_from_nav"
]
repository_url = "https://github.com/handcrafted-software/handcrafted-software.github.io"
